### PR TITLE
Redis Server Url Support & Dependency Update

### PR DESCRIPTION
**Pull request by Mohamed-Habshey**
Hi 

i submit this pr as i need to use redis as transport for my micro-services server deployed to heroku but to be able to use Heroku-redis addon  which require us to use **Redis Server Url Format** so i modified the plugin accordingly and tested on heroku.

# Use redis server Url and supply as param:
Provided how to use example in readme.
```js
require('seneca')({
 transport: {
    redis: {
      // you can use The URL of the Redis server. Format:-
      url: "[redis:]//[[user][:password@]][host][:port][/db-number][?db=dbnumber[&password=bar[&option=value]]]"
    }
  }
})
```

# Dependencies update 
```js
"lodash": "^4.14.1",
"redis": "~2.6.2"
```

#   Using quite() instead of the depreciated end() 
to cleanly end client connection to the server.
```js
redis_in.quit()
redis_out.quit()
```

Hope this Helps,

Regards
M.Habashy

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
@Mohamed-Habshey This looks nice. Just a couple of linting issues. If you run `npm run lint` it will tell you which ones.

**Comment by Mohamed-Habshey** [comment]
@mcdonnelldean  thanks  i believe i had fixed the linting issues  hope this helps

**Comment by mcdonnelldean** [comment]
@Mohamed-Habshey Cheers, I'll get this reviewed in the next couple of days.

**Comment by Mohamed-Habshey** [comment]
Awesome :+1:  looking forward for your review, Cheers

**Comment by mcdonnelldean** [comment]
@Mohamed-Habshey Could you remove the package.json bump and also add your details to the contributors list in package.json? I'll be merging this soon.

**Comment by Mohamed-Habshey** [comment]
@mcdonnelldean  done  :+1:  Thanks

**Comment by mcdonnelldean** [comment]
@Mohamed-Habshey Super stuff. I've merged. Should be a release before the end of the week, just a couple more org wide changes to go.

**Comment by Mohamed-Habshey** [comment]
That's Awesome  :smile:  @mcdonnelldean  Thank you so much, Much appreciated :+1: 
Best Wishes

**Pull request merged**
